# Generated by Django 3.2 on 2021-05-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=1024, verbose_name='string')),
                ('tokenized_string', models.CharField(editable=False, max_length=1024, verbose_name='tokenized string')),
            ],
            options={
                'verbose_name': 'pattern',
                'verbose_name_plural': 'patterns',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('simple_chatbot.responses.RecomendationResponse', 'Recomendation'), ('simple_chatbot.responses.GreetingResponse', 'Greeting')], max_length=120, unique=True, verbose_name='Method')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='UserMessageInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024, verbose_name='message')),
                ('status', models.BooleanField(blank=True, help_text='Message evaluation right or wrong?', null=True, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('correct_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermessageinput_corrected', to='simple_chatbot.tag', verbose_name='correct tag')),
                ('identified_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermessageinput_identified', to='simple_chatbot.tag', verbose_name='identified tag')),
            ],
            options={
                'verbose_name': 'user message input',
                'verbose_name_plural': 'user message inputs',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=40, unique=True, verbose_name='token')),
                ('patterns', models.ManyToManyField(blank=True, editable=False, related_name='tokens', to='simple_chatbot.Pattern')),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'tokens',
            },
        ),
        migrations.AddField(
            model_name='pattern',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patterns', to='simple_chatbot.tag', verbose_name='tag'),
        ),
    ]
