# Generated by Django 3.2 on 2021-05-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_chatbot', '0002_auto_20210501_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AlterField(
            model_name='tag',
            name='method',
            field=models.CharField(choices=[('simple_chatbot.responses.RecomendationResponse', 'Recomendation'), ('simple_chatbot.responses.GreetingResponse', 'Greeting')], max_length=120, unique=True, verbose_name='Method'),
        ),
    ]
